version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      # image: anyday-backend-app:latest
    restart: always
    environment:
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      - MAILJET_API_KEY=${MAILJET_API_KEY}
      - MAILJET_SECRET_KEY=${MAILJET_SECRET_KEY}
      - MAILJET_FROM=${MAILJET_FROM}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_TOKEN=${REDIS_TOKEN}
      - REDIS_PORT=${REDIS_PORT}
      - BASE_URL=${BASE_URL}
      - BACKEND_URL=${BACKEND_URL}
      - PORT=${PORT}
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    environment:
      REDIS_URL: ${REDIS_URL}
      REDIS_PORT: ${REDIS_PORT}

volumes:
  db-data:
  redis-data: