version: '3.8'
services:
  backend:
    image: anyday-backend-app:latest
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    ports:
      - '4000:8080'
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
