name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT }}/anyday-backend-app:latest .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/anyday-backend-app:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy anyday-backend-app \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/anyday-backend-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
