name: Build and Deploy to Google Cloud Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GAR_LOCATION: "us-central1"
      PROJECT_ID: "anyday-essay"
      REPO_NAME: "cloud-run-source-deploy"
      REGION: "us-central1"
      SERVICE_NAME: "anyday-backend-gcloudrun"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/anyday-essay-fastify-app:$GITHUB_SHA" .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/anyday-essay-fastify-app:$GITHUB_SHA"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/anyday-essay-fastify-app:$GITHUB_SHA" \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "FRONTEND_URL='${{ secrets.FRONTEND_URL }}',BACKEND_URL='${{ secrets.BACKEND_URL }}',APPSEC='${{ secrets.APPSEC }}',DATABASE_URL='${{ secrets.DATABASE_URL }}',POSTGRES_PRISMA_URL='${{ secrets.POSTGRES_PRISMA_URL }}',POSTGRES_URL_NONPOOLING='${{ secrets.POSTGRES_URL_NONPOOLING }}',MAILJET_API_KEY='${{ secrets.MAILJET_API_KEY }}',MAILJET_SECRET_KEY='${{ secrets.MAILJET_SECRET_KEY }}',REDIS_HOST='${{ secrets.REDIS_HOST }}',REDIS_PORT='${{ secrets.REDIS_PORT }}',REDIS_PASSWORD='${{ secrets.REDIS_PASSWORD }}',REGISTER_EXPIRATION=${{ secrets.REGISTER_EXPIRATION }},NODE_ENV='${{ secrets.NODE_ENV }}',STRIPE_SECRET_KEY='${{ secrets.STRIPE_SECRET_KEY }}',STRIPE_WEBHOOK_SECRET='${{ secrets.STRIPE_WEBHOOK_SECRET }}',BUCKET_URL='${{ secrets.BUCKET_URL }}',GRAPHQL_API_URL='${{ secrets.GRAPHQL_API_URL }}',GRAPHQL_API_TOKEN='${{ secrets.GRAPHQL_API_TOKEN }}'"
