<<<<<<< HEAD
name: Build and Deploy to Google Cloud Artifact Registry
=======
name: Build and Deploy to Google Cloud Run
>>>>>>> e7c503d741dbc5a1650205c775bff16f09a89214

on:
  push:
    branches:
      - main
<<<<<<< HEAD
=======
  workflow_dispatch:
>>>>>>> e7c503d741dbc5a1650205c775bff16f09a89214

jobs:
  build:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    env:
      GAR_LOCATION: "us-central1"
      PROJECT_ID: "anyday-essay"
      REPO_NAME: "cloud-run-source-deploy"
      REGION: "us-central1"
      SERVICE_NAME: "anyday-backend-gcloudrun"

=======
>>>>>>> e7c503d741dbc5a1650205c775bff16f09a89214
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

<<<<<<< HEAD
      - name: Authenticate to Google Cloud
=======
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Google Cloud
>>>>>>> e7c503d741dbc5a1650205c775bff16f09a89214
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
<<<<<<< HEAD
          gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/anyday-essay-fastify-app:$GITHUB_SHA" .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/anyday-essay-fastify-app:$GITHUB_SHA"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/anyday-essay-fastify-app:$GITHUB_SHA" \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \

      - name: Verify deployment
        run: |
          gcloud run services describe $SERVICE_NAME --region $REGION --format="json"
=======
          gcloud auth configure-docker

      - name: Build Docker image and Push to Google Container Registry
        run: |
          docker build -t gcr.io/anydayessay/anyday-backend-app:latest --push .

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy anyday-backend-app \
            --image gcr.io/anydayessay/anyday-backend-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
>>>>>>> e7c503d741dbc5a1650205c775bff16f09a89214
