name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          !**/node_modules/**/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/anyday-backend-app:latest .

    - name: Bronze 1
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/anyday-backend-app:latest

    - name: Configure gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy anyday-backend-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/anyday-backend-app:latest \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --port 8080
