name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build Docker image and Push to Google Container Registry
        run: |
          docker build -t us-docker.pkg.dev/anyday-essay/anyday-essay-fastify-app:latest --push .

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy anyday-essay-fastify-app \
            --image us-docker.pkg.dev/anyday-essay/anyday-essay-fastify-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
             --service-account github-actions@anyday-essay.iam.gserviceaccount.com \
            --no-traffic \
            --logging=cloud-logging-only
