name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '**/app/**'
      - '.github/workflows/**'
      - 'prisma/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Authenticate Docker with Google Cloud
        run: gcloud auth configure-docker
